# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "089f9d6cac14ea569e1c2855fec71300"
name = "remix-app"
application_url = "https://customized-totally-lending-consultancy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bitdev-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://customized-totally-lending-consultancy.trycloudflare.com/auth/callback",
  "https://customized-totally-lending-consultancy.trycloudflare.com/auth/shopify/callback",
  "https://customized-totally-lending-consultancy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
